// <auto-generated />
using System;
using EVALUACION.INFRASTRUCTURE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EVALUACION.INFRASTRUCTURE.Migrations
{
    [DbContext(typeof(OCContext))]
    partial class OCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:EVALUACION.HP_OC_DET_seq", "'HP_OC_DET_seq', 'EVALUACION', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:EVALUACION.HP_OC_seq", "'HP_OC_seq', 'EVALUACION', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EVALUACION.DOMAIN.AggregatesModel.OCAggregate.HP_OC", b =>
                {
                    b.Property<int>("ID_HP_OC")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "HP_OC_seq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "EVALUACION")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("FECHA_REGISTRO");

                    b.Property<int>("N_ID_ESTADO");

                    b.Property<int>("N_ID_PROVEEDOR");

                    b.HasKey("ID_HP_OC")
                        .HasName("PK_ID_HP_OC");

                    b.ToTable("HP_OC","EVALUACION");
                });

            modelBuilder.Entity("EVALUACION.DOMAIN.AggregatesModel.OCAggregate.HP_OC_DET", b =>
                {
                    b.Property<int>("N_ID_OC_DET")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "HP_OC_DET_seq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "EVALUACION")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("FECHA_ESTIMADA");

                    b.Property<int>("ID_FABRICANTE");

                    b.Property<int>("ID_HP_OC");

                    b.Property<int>("ID_PRODUCTO");

                    b.Property<string>("OBSERVACION")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TURNO")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1)");

                    b.HasKey("N_ID_OC_DET")
                        .HasName("PK_HP_OC_DET");

                    b.HasIndex("ID_HP_OC");

                    b.ToTable("HP_OC_DET","EVALUACION");
                });

            modelBuilder.Entity("EVALUACION.DOMAIN.AggregatesModel.OCAggregate.HP_OC_DET", b =>
                {
                    b.HasOne("EVALUACION.DOMAIN.AggregatesModel.OCAggregate.HP_OC", "HP_OC")
                        .WithMany("hP_OC_DETs")
                        .HasForeignKey("ID_HP_OC")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
